-- VAICĀJUMS ATROD UZŅĒMUMU NOSAUKUMUS
SELECT nosaukums FROM uznemums;

-- VAICĀJUMS SAKĀRTO DARBINIEKUS PĒC VECUMA DILSTOŠĀ SECĪBĀ
SELECT * FROM darbinieks ORDER BY VECUMS DESC;

-- VAICĀJUMS ATROD 5 VECĀKO DARBINIEKU DARBA VIETAS
SELECT TOP 5 darbavieta FROM darbinieks ORDER BY VECUMS DESC;

-- VAICĀJUMS ATROD UZŅĒMUMUS, KUROS STRĀDĀ 5 VECĀKIE DARBINIEKI
SELECT nosaukums FROM uznemums WHERE uznemums.ID IN (SELECT TOP 5 darbavieta FROM darbinieks ORDER BY VECUMS DESC);